peliculasMasVistas = [
  "Avatar",
  "Vengadores: Endgame",
  "Avatar: El sentido del agua",
  "Titanic",
  "Star Wars: Episodio VII - El despertar de la Fuerza",
  "Vengadores: Infinity War",
  "Spider-Man: No Way Home",
  "Jurassic World",
  "El Rey León",
  "Los Vengadores",
  "Rápidos y Furiosos 7",
  "Top Gun: Maverick",
  "Frozen II",
  "Vengadores: La era de Ultrón",
  "Black Panther",
  "Star Wars: Episodio VIII - Los últimos Jedi",
  "Harry Potter y las Reliquias de la Muerte - Parte 2",
  "Jurassic World: El reino caído",
  "La Bella y la Bestia",
  "Frozen",
  "Los Increíbles 2",
  "Rápidos y Furiosos 8",
  "Iron Man 3",
  "Minions",
  "Capitán América: Civil War",
  "Aquaman",
  "Spider-Man: Lejos de casa",
  "Capitana Marvel",
  "Transformers: El lado oscuro de la luna",
  "Skyfall",
  "Transformers: La era de la extinción",
  "El caballero oscuro: La leyenda renace",
  "Joker",
  "Star Wars: Episodio IX - El ascenso de Skywalker",
  "Toy Story 4",
  "Toy Story 3",
  "Piratas del Caribe: El cofre del hombre muerto",
  "Rogue One: Una historia de Star Wars",
  "Aladdín",
  "Piratas del Caribe: En mareas misteriosas",
  "Mi villano favorito 3",
  "Buscando a Dory",
  "Alicia en el país de las maravillas",
  "Zootopia",
  "El Hobbit: Un viaje inesperado",
  "El caballero oscuro",
  "Jurassic World: Dominion",
  "Oppenheimer",
  "Harry Potter y la piedra filosofal",
  "Mi villano favorito 2",
  "El libro de la selva",
  "Jumanji: Bienvenidos a la jungla",
  "Piratas del Caribe: En el fin del mundo",
  "Harry Potter y las Reliquias de la Muerte - Parte 1",
  "El Hobbit: La desolación de Smaug",
  "El Hobbit: La batalla de los cinco ejércitos",
  "Doctor Strange en el multiverso de la locura",
  "Harry Potter y la Orden del Fénix",
  "Minions: Nace un villano",
  "El Señor de los Anillos: Las dos torres",
  "Harry Potter y el misterio del príncipe",
  "Shrek 2"
]